# -*- coding: utf-8 -*-
"""d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nUXWeAoEaC_Vrj14coxyNH-yFNFf1JRi
"""

# ============================================================
# Tech Consulting Interview Simulator – Streamlit (Day 1 + Day 2)
# Author: GPT-5 (for Kavinesan K)
# Purpose: Consulting-grade interactive MCQ quiz with hints,
#          50/50, scoring, streaks, and full explanations.
# Deploy free on https://share.streamlit.io
# ============================================================

import random, textwrap
import streamlit as st

# ===================== QUIZ BANK =============================

quiz_bank = {
    "Day 1 – Networking Basics": [
        {
            "q": "Which device primarily operates at OSI Layer 2?",
            "choices": [
                {"text": "Router", "ex": "Routers are Layer 3 and forward on IP."},
                {"text": "Switch", "ex": "✅ Correct – forwards frames using MAC addresses at Layer 2."},
                {"text": "Gateway", "ex": "Protocol translation at higher layers."},
                {"text": "Repeater", "ex": "Layer 1 device that only regenerates signals."}
            ],
            "answer": 1, "hint": "Think MAC vs IP."
        },
        {
            "q": "Best description of routing?",
            "choices": [
                {"text": "Broadcasting frames to all ports", "ex": "That’s switching without VLANs."},
                {"text": "Selecting paths between networks using IP addresses", "ex": "✅ Correct – Layer 3 path selection."},
                {"text": "Encrypting traffic between hosts", "ex": "Security, not routing."},
                {"text": "Assigning IPs automatically", "ex": "That’s DHCP, not routing."}
            ],
            "answer": 1, "hint": "Layer 3 = IP and path choice."
        },
        {
            "q": "Primary purpose of VLANs?",
            "choices": [
                {"text": "Boost Wi-Fi signal", "ex": "Radio power unrelated."},
                {"text": "Logically segment broadcast domains", "ex": "✅ Correct – controls broadcasts and adds security."},
                {"text": "Encrypt internet traffic", "ex": "VPN does that."},
                {"text": "Replace routing entirely", "ex": "Inter-VLAN routing still needed."}
            ],
            "answer": 1, "hint": "Broadcast domain control."
        },
        {
            "q": "Client reports network slowness. First diagnostic move?",
            "choices": [
                {"text": "Replace all switches", "ex": "Premature and expensive."},
                {"text": "Layered triage: Physical → L2 → L3 → Transport", "ex": "✅ Correct – use the OSI model systematically."},
                {"text": "Upgrade to 10 Gb everywhere", "ex": "Costly without root cause."},
                {"text": "Disable firewalls", "ex": "High risk and no diagnostic value."}
            ],
            "answer": 1, "hint": "Use OSI as your checklist."
        },
        {
            "q": "TCP vs UDP - which is true?"
        }
